services:
    web_challenge:
        build: ./web-challenges
        depends_on:
            - db
        ports:
            - "3000:8000"
        networks:
            - ctf-network
      
    db:
        image: postgres:latest 
        environment:
            - POSTGRES_DB=ctf_db
            - POSTGRES_USER=ctf_user
            - POSTGRES_PASSWORD=ctf_pass
        restart: always
        ports:
            - "3001:5432"
        networks:
            - ctf-network

volumes:
  postgres_data:

networks:
    ctf-network:
        driver: bridge